# Generated by Django 3.2.11 on 2022-02-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20220201_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_list',
            new_name='user',
        ),
    ]
